ibw_jobeet_homepage:
    path:     /hello/{name}
    defaults: { _controller: IbwJobeetBundle:Default:index }
    
IbwJobeetBundle_job:
        resource: "@IbwJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job
        
ibw_jobeet_homepage:
    pattern:  /
    defaults: { _controller: IbwJobeetBundle:Job:index }
